# Generated by Django 5.1.3 on 2024-11-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='reduction_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
