# Generated by Django 5.1.3 on 2024-11-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='budget_float',
            field=models.FloatField(default=50, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='contact_text',
            field=models.CharField(default='', max_length=200, verbose_name='Other ways to contact'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='deadline_date',
            field=models.DateTimeField(verbose_name='Deadline (format YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='description_text',
            field=models.CharField(default='', max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='email_text',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='features_text',
            field=models.CharField(default='', max_length=200, verbose_name='Specific Features'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='itemname_text',
            field=models.CharField(max_length=50, verbose_name='Name of Commission'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='username_text',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='material_list',
            field=models.JSONField(default={'Cloth': 'A lot'}),
        ),
    ]
