# Generated by Django 5.1.3 on 2024-12-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_commission_budget_float_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='deadline_date',
            field=models.DateTimeField(verbose_name='Deadline (format d/m/Y)'),
        ),
    ]
